### ISSUE TITLE
Laravel 11 support

### ISSUE THREAD

**Issue by lukasmedia** [Gared/shelly-php-client#3]
Hi please, laravel 11 support

Problem 1
    - symfony/property-info[v5.2.0, ..., v5.3.14] require symfony/deprecation-contracts ^2.1 -> found symfony/deprecation-contracts[v2.1.0, ..., v2.5.3] but the package is fixed to v3.5.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - symfony/property-info[v5.4.0, ..., v5.4.42] require symfony/string ^5.1|^6.0 -> found symfony/string[v5.1.0, ..., v5.4.42, v6.0.0, ..., v6.4.10] but the package is fixed to v7.1.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - gared/shelly-php-client[1.0.0, 2.0.0, ..., 2.0.1] require symfony/property-info ^5.2 -> satisfiable by symfony/property-info[v5.2.0, ..., v5.4.42].
    - Root composer.json requires gared/shelly-php-client * -> satisfiable by gared/shelly-php-client[1.0.0, 2.0.0, 2.0.1].

**Comment by Gared** [comment]
@lukasmedia Thx for your bug report. I released version 2.1.0 with updated version constraints. Please test if this works for you :-)
